# name: $(BuildID).$(Date:yyyyMMdd)
variables:
    MAJOR_MINOR: "1.0"
    LLVM: "12"

jobs:

  - job: Serializers_On_Linux
    variables:
      OS: Linux
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

trigger:
  - master

pr:
  branches:
    exclude:
      - '*'
