# name: $(BuildID).$(Date:yyyyMMdd)
variables:
    MAJOR_MINOR: "0.1"

jobs:

  - job: Serializers_On_Focal
    variables:
      OS: Linux
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-nix.yml

trigger:
  - master

pr:
  branches:
    exclude:
      - '*'
