name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: System Info
      run: |
        script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash
        Say "Environment"
        printenv | sort
        Say "Free Space"
        df -T
        Say "CPU"
        cat /proc/cpuinfo
        Say "dotnet --info"
        dotnet --info
        
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Reinstall dotnet and BenchmarkDotNet.Tool
      run: |
        # dotnet tool install -g BenchmarkDotNet.Tool
        export DOTNET_TARGET_DIR=/usr/share/dotnet
        curl -ksSL -o /tmp/install-DOTNET.sh https://raw.githubusercontent.com/devizer/test-and-build/master/lab/install-DOTNET.sh; 
        bash /tmp/install-DOTNET.sh;
        sudo ln -f -s ${DOTNET_TARGET_DIR}/dotnet /usr/local/bin/dotnet
    - name: dotnet --info
      run: dotnet --info; Say "PATH is [$PATH]"
    - name: Benchmark
      run: dotnet benchmark --runtimes netcoreapp3.1 -f '*' **/*.Benchmark.exe
         
